version: 2
dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install make
jobs:
  build:
    working_directory: ~/meo
    docker:
      - image: circleci/clojure:lein-2.8.1-node
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: lein deps
      - run: lein test
      - run: npm install
      - run: lein cljs-main
      - run: lein cljs-renderer
      - run: lein cljs-updater
      - run: lein sass
      - run: lein uberjar
      - store_artifacts:
          path: test2junit/html/
          destination: reports
